config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  namespace :admin do #網頁後台路由
    resources :restaurants
    resources :categories
    root "restaurants#index" 
  end

  resources :categories, only: :show
  resources :restaurants, only: [:index, :show, :edit, :update]
  root "restaurants#index" #網頁前台首頁

  resources :restaurants, only: [:index, :show] do
    resources :comments, only: [:create, :destroy]
  end
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  validates_presence_of :name
  has_many :restaurants, dependent: :destroy
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :restaurant
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  validates_presence_of :name
  belongs_to :category
  has_many_attached :menu_uploads
  has_many :comments

  scope :category, -> (category_id) { where category_id: category_id }
  scope :district, -> (district){ where district: district }
end

app/models/user.rb
class User < ApplicationRecord
  
  enum role: {user:0, vip:1, admin:2}

  after_initialize :set_default_role, :if => :new_record?

  def set_default_role
    self.role ||= :user
  end


  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  has_many :comments
end

app/controllers/admin/base_controller.rb
class Admin::BaseController < ApplicationController
  before_action :authenticate_admin

  private

  def authenticate_admin
    unless current_user.admin?
      flash[:alert] = "Not allow!"
      redirect_to root_path
    end
  end
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < Admin::BaseController
  before_action :set_category, only: [:update, :destroy]

  def index
    @categories = Category.all
    if params[:id]
      set_category
    else
      @category = Category.new
    end
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      flash[:notice] = "category was successfully created"
      redirect_to admin_categories_path

    else
      @categories = Category.all
      render :index
    end
  end

  def update
    if @category.update(category_params)
      flash[:notice] = "category was successfully updated"
      redirect_to admin_categories_path

    else
      @categories = Category.all
      render :index
    end
  end

  def destroy
    @category.destroy
    flash[:alert] = "category was successfully deleted"
    redirect_to admin_categories_path
  end
  
  private

  def category_params
    params.require(:category).permit(:name)
  end

  def set_category
  @category = Category.find(params[:id])
  end

end

app/controllers/admin/restaurants_controller.rb
class Admin::RestaurantsController < Admin::BaseController
  before_action :set_restaurant, only: [:show, :edit, :update, :destroy]
  include Pagy::Backend

  def index
    @restaurants = Restaurant.all
    @pagy, @restaurants = pagy(Restaurant.all, items: 20)
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    if @restaurant.save
      flash[:notice] = "restaurant was successfully created"
      redirect_to admin_restaurants_path
    else
      flash.now[:alert] = "restaurant was failed to create"
      render :new
    end
  end

  def show
    
  end

  def edit
  end

  def update
    if @restaurant.update(restaurant_params)
      flash[:notice] = "restaurant was successfully updated"
      redirect_to admin_restaurant_path(@restaurant)
    else
      flash.now[:alert] = "restaurant was failed to update"
      render :edit
    end
  end

  def destroy
    @restaurant.destroy
    redirect_to admin_restaurants_path
    flash[:alert] = "restaurant was deleted"
  end

  private

  def restaurant_params
    params.require(:restaurant).permit(:name, :tel, :address, :description, :category_id, menu_uploads: [])
  end

  def set_restaurant
    @restaurant = Restaurant.find(params[:id]) 
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  include Pagy::Backend

  def show
    @category = Category.find(params[:id])
    @pagy, @restaurants = pagy(@category.restaurants, items: 10)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    @restaurant = Restaurant.find(params[:restaurant_id])
    @comment = @restaurant.comments.build(comment_params)
    @comment.user = current_user
    @comment.save!
    redirect_to restaurant_path(@restaurant)
  end

  def destroy
    @restaurant = Restaurant.find(params[:restaurant_id])
    @comment = Comment.find(params[:id])

    if current_user.admin?
      @comment.destroy
      redirect_to restaurant_path(@restaurant)
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:content)
  end

  end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :set_restaurant, only: [:show, :edit, :update]
  before_action :authorize_only, :except => [:index, :show] 
  

  include Pagy::Backend

  def index
    @categories = Category.all
    @districts = Restaurant.distinct.pluck(:district)
    @restaurants = Restaurant.where(nil) 
    @restaurants = @restaurants.category(params[:category]) if params[:category].present?
    @restaurants = @restaurants.district(params[:district]) if params[:district].present?
    @pagy, @restaurants = pagy(@restaurants, items: 20)
  end

  def show
    @comment = Comment.new
  end

  def edit
  end

  def update
    if @restaurant.update(restaurant_params)
      flash[:notice] = "restaurant was successfully updated"
      redirect_to restaurant_path(@restaurant)
    else
      flash.now[:alert] = "restaurant was failed to update"
      render :edit
    end
  end

  private

  def restaurant_params
    params.require(:restaurant).permit(:name, :tel, :address, :description, :category_id, menu_uploads: [])
  end

  def set_restaurant
    @restaurant = Restaurant.find(params[:id]) 
  end

  def authorize_only
    unless current_user.admin? || current_user.vip?
      redirect_to restaurant_path(@restaurant), :alert => "Access denied."
    end
  end

end

app/helpers/admin/categories_helper.rb
module Admin::CategoriesHelper
end

app/helpers/admin/restaurants_helper.rb
module Admin::RestaurantsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  include Pagy::Frontend
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/views/admin/categories/index.html.erb
<div class="container">

  <h1>餐廳分類總表</h1>
  <div>
    <%= link_to 'Restaurant', admin_restaurants_path %> |
    <%= link_to 'Categories', admin_categories_path %>
  </div>

  <div class="form-inline" >
  <%= form_for [:admin, @category] do |f| %>
    <div class="form-group">
      <%= f.text_field :name, placeholder: "Category Name",  class: "form-control" %>
    </div>
    <%= f.submit class: "btn btn-primary" %>
  <% end %>
  </div>

  <div class="row">

    <div class="col-md-12">

      <table class="table table-striped table-bordered">
        <thead>
          <tr>
            <th>#</th>
            <th>餐廳分類</th>
            <th>可執行動作</th>
          </tr>
        </thead>
        <tbody>
          <% @categories.each do |category| %>
          <tr>
            <th scope="row"><%= category.id %></th>
            <td><%= category.name %></td>
            <td><%= link_to 'Edit', admin_categories_path(id: category.id) %> | 
            <%= link_to 'Delete', admin_category_path(category), method: :delete, data: { confirm: "Are you sure?"} %></td>
          </tr>
          <% end %>
        </tbody>
      </table>

    </div>

  </div>
</div>

app/views/admin/restaurants/_form.html.erb
<div class="container">
  <div class="row">
    <% if @restaurant.errors.any? %>
      <h4>We have some errors here !</h4>
      <ul>
        <% @restaurant.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
      <hr>
    <% end %> 
      <%= form_for [:admin, @restaurant] do |f| %>
       <div class="form-group">
        <%= f.label :name, "餐廳名稱" %>
        <%= f.text_field :name, class: "form-control" %>
      </div>
      <div>
        <%= f.label :category, "餐廳分類" %>
        <%= f.collection_select :category_id, Category.all, :id, :name, {prompt: true}, {class: "form-control"} %>
      </div>
      <div class="form-group">
        <%= f.label :address, "地址" %>
        <%= f.text_field :address, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :description, "餐廳描述" %>
        <%= f.text_area :description, class: "form-control" %>
      <div class="field">
        <%= f.label :menu_uploads %>
        <%= f.file_field :menu_uploads, multiple: true %>
      </div>
      </div>
      <div class="form-group">
        <%= f.submit class: "btn btn-primary" %>
      </div>
    <% end %>
  </div>
</div>

app/views/admin/restaurants/edit.html.erb
<%= render partial: "form" %>

app/views/admin/restaurants/index.html.erb
<div class="container">

  <h1>餐廳後台</h1>
  <div>
    <%= link_to 'Restaurant', admin_restaurants_path %> |
    <%= link_to 'Categories', admin_categories_path %>
  </div>

  <div class="row">

    <div class="col-md-12">

      <div>
        <%= link_to 'New Restaurant', new_admin_restaurant_path, class: "btn btn-primary" %>
      </div>
      <br>
      <table class="table table-striped table-bordered">
        <thead>
          <tr>
            <th>#</th>
            <th>餐廳分類</th>
            <th>餐廳名稱</th>
            <th>可執行動作</th>
          </tr>
        </thead>
        <tbody>
          <% @restaurants.each do |restaurant| %>
          <tr>
            <th scope="row"><%= restaurant.id %></th>
            <td><%= restaurant.category.name %></td>
            <td><%= restaurant.name %></td>
            <td>
              <%= link_to 'Show', admin_restaurant_path(restaurant) %>
              <%= link_to 'Edit', edit_admin_restaurant_path(restaurant) %>
              <%= link_to 'Delete', admin_restaurant_path(restaurant), method: :delete, data: { confirm: "Are you sure?"} %>
            </td>
          </tr>
          <% end %>
        </tbody>
      </table>

      <div class="text-center">
        <%= pagy_nav_compact_bootstrap(@pagy).html_safe %>
      </div>

    </div>

  </div>
</div>

app/views/admin/restaurants/new.html.erb
<% if @restaurant.errors.any? %>
  <h2>We have some errors here !</h2>
  <ul>
    <% @restaurant.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>

<%= form_for  [:admin, @restaurant] do |f| %>
  <%= f.label :name, "Name" %>
  <%= f.text_field :name %>

  <%= f.label :tel, "Tel" %>
  <%= f.text_field :tel %>

  <%= f.label :address, "Address" %>
  <%= f.text_field :address %>

  <%= f.label :description, "Description" %>
  <%= f.text_area :description %>

  <%= f.submit %>
<% end %>

app/views/admin/restaurants/show.html.erb
<h1><%= @restaurant.name %></h1>
<%= @restaurant.category.name %><br>
Tel: <%= @restaurant.tel %><br>
Address: <%= @restaurant.address %><br>
Description:<%= @restaurant.description %><br>

</p>
  <% if @restaurant.menu_uploads.attached? %>
    <p> 
    <h2>Menu</h2>
    <% @restaurant.menu_uploads.each_with_index do |menu, i| %>
    <p> 
    <%= link_to("menu##{i}", rails_blob_path(menu, disposition: "attachment")) %>
    <%= image_tag(menu) %>
    </p>
  <% end %>
  </p>
<% end %>

<br>

<%= link_to 'Back to index', admin_restaurants_path %>

app/views/categories/show.html.erb
<div class="content"> 
    <% @restaurants.each do |restaurant| %>
    <div class="display">
      <h2><%= link_to restaurant.name, restaurant_path(restaurant) %></h2>
      <p><%= restaurant.district %><p>
      <p><%= restaurant.category.name %><p>
    </div>
    <% end %>
  <%= pagy_nav_compact_bootstrap(@pagy).html_safe %>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Menusite</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-default">
      <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%= link_to "Menusite", root_path, class: "navbar-brand" %>
        </div>
         <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="pull-right text-right nav navbar-nav">
            <% if current_user %>
            <li><p class="navbar-text">Hi, <%= current_user.email %></p></li>
            <li><%= link_to('登出', destroy_user_session_path, method: :delete) %></li>
            <li><%= link_to('修改密碼', edit_user_registration_path) %></li>
            <% else %>
            <li><%= link_to('註冊', new_user_registration_path) %></li>
            <li><%= link_to('登入', new_user_session_path) %></li>
            <% end %>
          </ul>
        </div>
      </div>
    </nav>

    <% if flash[:notice] %>
    <div class="container">
      <div class="row">
        <div class="alert alert-success alert-dismissible" role="alert">
          <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          <%= notice %>
        </div>
      </div>
    </div>
    <% end %>

    <% if flash[:alert] %>
    <div class="container">
      <div class="row">
        <div class="alert alert-danger alert-dismissible" role="alert">
          <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          <%= alert %>
        </div>
      </div>
    </div>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/restaurants/edit.html.erb
<div class="container">
  <div class="row">
    <% if @restaurant.errors.any? %>
      <h4>We have some errors here !</h4>
      <ul>
        <% @restaurant.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
      <hr>
    <% end %> 
      <%= form_for [@restaurant] do |f| %>
       <div class="form-group">
        <%= f.label :name, "餐廳名稱" %>
        <%= f.text_field :name, class: "form-control" %>
      </div>
      <div>
        <%= f.label :category, "餐廳分類" %>
        <%= f.collection_select :category_id, Category.all, :id, :name, {prompt: true}, {class: "form-control"} %>
      </div>
      <div class="form-group">
        <%= f.label :address, "地址" %>
        <%= f.text_field :address, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :description, "餐廳描述" %>
        <%= f.text_area :description, class: "form-control" %>
      <div class="field">
        <%= f.label :menu_uploads %>
        <%= f.file_field :menu_uploads, multiple: true %>
      </div>
      </div>
      <div class="form-group">
        <%= f.submit class: "btn btn-primary" %>
      </div>
    <% end %>
  </div>
</div>

app/views/restaurants/index.html.erb
<div class="wrap">
  <div class="search_section">

  </div>
  <div class="filter_bar">
    <h3>餐廳種類</h3>
    <% @categories.each do |category| %>
      <p><%= link_to category.name, request.query_parameters.merge(category: category.id) %></p>
    <% end %>
    <h3>餐廳地區</h3>
    <% @districts.each do |district| %>
      <p><%= link_to district, request.query_parameters.merge(district: district) %></p>
    <% end %>
  </br>
  <h3><%= link_to "重新篩選", restaurants_path %></h3>
  </div> 
  <div class="content"> 
    <% @restaurants.each do |restaurant| %>
    <div class="display">
      <h2><%= link_to restaurant.name, restaurant_path(restaurant) %></h2>
      <p><%= restaurant.district %><p>
      <p><%= restaurant.category.name %><p>
    </div>
    <% end %>
  <%= pagy_nav_compact_bootstrap(@pagy).html_safe %>
  </div>
</div>

app/views/restaurants/show.html.erb
<h1><%= @restaurant.name %></h1>
<%= @restaurant.category.name %><br>
Tel: <%= @restaurant.tel %><br>
Address: <%= @restaurant.address %><br>
Description:<%= @restaurant.description %><br>
</p>
  <% if @restaurant.menu_uploads.attached? %>
    <p> 
    <h2>Menu</h2>
    <% @restaurant.menu_uploads.each_with_index do |menu, i| %>
    <p> 
    <%= link_to("menu##{i}", rails_blob_path(menu, disposition: "attachment")) %>
    <%= image_tag(menu) %>
    </p>
  <% end %>
  </p>
<% end %>

<br>

<div class="container">
  <div class="row">
   <%= form_for [@restaurant, @comment] do |f| %>
    <div class="form-group">
      <%= f.text_area :content, placeholder: "留下評論", class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.submit class: "btn btn-primary" %>
      <%= f.button "Cancel", type: :reset, class: "btn btn-default" %>
    </div>
  <% end %>
  </div>
</div>

  <% @restaurant.comments.each do |comment| %>
    <div>
      <h4><%= comment.user.email.split("@")[0] %></h4>
      <p><%= simple_format comment.content %></p>
      <p class="text-muted">
        <em><%= comment.created_at %> </em>
      <% if current_user.admin? %>
        <%= link_to "Delete", restaurant_comment_path(@restaurant, comment), method: :delete %>
      <% end %>
      </p>
    </div>
    <hr>
  <% end %>

<% if current_user.vip? || current_user.admin? %>
   <%= link_to 'Edit', edit_restaurant_path %>
<% end %>

<br>
<%= link_to '回到餐廳列表', restaurants_path %>